//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.JetSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://www.jetsms.net/soap/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendSMSResult", Namespace="https://www.jetsms.net/soap/")]
    [System.SerializableAttribute()]
    public partial class SendSMSResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportSMSResult", Namespace="https://www.jetsms.net/soap/")]
    [System.SerializableAttribute()]
    public partial class ReportSMSResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.jetsms.net/soap/", ConfigurationName="JetSms.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendSMS", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.SendSMSResponse SendSMS(SahinRektefiyeSoln.JetSms.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSResponse> SendSMSAsync(SahinRektefiyeSoln.JetSms.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendTCKNSMS", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse SendTCKNSMS(SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendTCKNSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse> SendTCKNSMSAsync(SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendSMSAdvanced", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse SendSMSAdvanced(SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/SendSMSAdvanced", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse> SendSMSAdvancedAsync(SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportSMS", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.ReportSMSResponse ReportSMS(SahinRektefiyeSoln.JetSms.ReportSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportSMSResponse> ReportSMSAsync(SahinRektefiyeSoln.JetSms.ReportSMSRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportOriginator", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.ReportOriginatorResponse ReportOriginator(SahinRektefiyeSoln.JetSms.ReportOriginatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportOriginator", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportOriginatorResponse> ReportOriginatorAsync(SahinRektefiyeSoln.JetSms.ReportOriginatorRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace https://www.jetsms.net/soap/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportQuota", ReplyAction="*")]
        SahinRektefiyeSoln.JetSms.ReportQuotaResponse ReportQuota(SahinRektefiyeSoln.JetSms.ReportQuotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.jetsms.net/soap/ReportQuota", ReplyAction="*")]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportQuotaResponse> ReportQuotaAsync(SahinRektefiyeSoln.JetSms.ReportQuotaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(SahinRektefiyeSoln.JetSms.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string originator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string expiredate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString messages;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString receipents;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            this.user = user;
            this.password = password;
            this.originator = originator;
            this.reference = reference;
            this.startdate = startdate;
            this.expiredate = expiredate;
            this.messages = messages;
            this.receipents = receipents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(SahinRektefiyeSoln.JetSms.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(SahinRektefiyeSoln.JetSms.SendSMSResult SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTCKNSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTCKNSMS", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendTCKNSMSRequestBody Body;
        
        public SendTCKNSMSRequest() {
        }
        
        public SendTCKNSMSRequest(SahinRektefiyeSoln.JetSms.SendTCKNSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendTCKNSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string originator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string expiredate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString messages;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString receipents;
        
        public SendTCKNSMSRequestBody() {
        }
        
        public SendTCKNSMSRequestBody(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            this.user = user;
            this.password = password;
            this.originator = originator;
            this.reference = reference;
            this.startdate = startdate;
            this.expiredate = expiredate;
            this.messages = messages;
            this.receipents = receipents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendTCKNSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendTCKNSMSResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendTCKNSMSResponseBody Body;
        
        public SendTCKNSMSResponse() {
        }
        
        public SendTCKNSMSResponse(SahinRektefiyeSoln.JetSms.SendTCKNSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendTCKNSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendTCKNSMSResult;
        
        public SendTCKNSMSResponseBody() {
        }
        
        public SendTCKNSMSResponseBody(SahinRektefiyeSoln.JetSms.SendSMSResult SendTCKNSMSResult) {
            this.SendTCKNSMSResult = SendTCKNSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSAdvancedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSAdvanced", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequestBody Body;
        
        public SendSMSAdvancedRequest() {
        }
        
        public SendSMSAdvancedRequest(SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendSMSAdvancedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string originator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string reference;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string startdate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string expiredate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString messages;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString receipents;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string messageType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString messageHeader;
        
        public SendSMSAdvancedRequestBody() {
        }
        
        public SendSMSAdvancedRequestBody(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents, string messageType, SahinRektefiyeSoln.JetSms.ArrayOfString messageHeader) {
            this.user = user;
            this.password = password;
            this.originator = originator;
            this.reference = reference;
            this.startdate = startdate;
            this.expiredate = expiredate;
            this.messages = messages;
            this.receipents = receipents;
            this.messageType = messageType;
            this.messageHeader = messageHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSAdvancedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSAdvancedResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponseBody Body;
        
        public SendSMSAdvancedResponse() {
        }
        
        public SendSMSAdvancedResponse(SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class SendSMSAdvancedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendSMSAdvancedResult;
        
        public SendSMSAdvancedResponseBody() {
        }
        
        public SendSMSAdvancedResponseBody(SahinRektefiyeSoln.JetSms.SendSMSResult SendSMSAdvancedResult) {
            this.SendSMSAdvancedResult = SendSMSAdvancedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportSMS", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportSMSRequestBody Body;
        
        public ReportSMSRequest() {
        }
        
        public ReportSMSRequest(SahinRektefiyeSoln.JetSms.ReportSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string status;
        
        public ReportSMSRequestBody() {
        }
        
        public ReportSMSRequestBody(string user, string password, string groupid, string status) {
            this.user = user;
            this.password = password;
            this.groupid = groupid;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportSMSResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportSMSResponseBody Body;
        
        public ReportSMSResponse() {
        }
        
        public ReportSMSResponse(SahinRektefiyeSoln.JetSms.ReportSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportSMSResult[] ReportSMSResult;
        
        public ReportSMSResponseBody() {
        }
        
        public ReportSMSResponseBody(SahinRektefiyeSoln.JetSms.ReportSMSResult[] ReportSMSResult) {
            this.ReportSMSResult = ReportSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportOriginatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportOriginator", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportOriginatorRequestBody Body;
        
        public ReportOriginatorRequest() {
        }
        
        public ReportOriginatorRequest(SahinRektefiyeSoln.JetSms.ReportOriginatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportOriginatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ReportOriginatorRequestBody() {
        }
        
        public ReportOriginatorRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportOriginatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportOriginatorResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportOriginatorResponseBody Body;
        
        public ReportOriginatorResponse() {
        }
        
        public ReportOriginatorResponse(SahinRektefiyeSoln.JetSms.ReportOriginatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportOriginatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SahinRektefiyeSoln.JetSms.ArrayOfString ReportOriginatorResult;
        
        public ReportOriginatorResponseBody() {
        }
        
        public ReportOriginatorResponseBody(SahinRektefiyeSoln.JetSms.ArrayOfString ReportOriginatorResult) {
            this.ReportOriginatorResult = ReportOriginatorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportQuotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportQuota", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportQuotaRequestBody Body;
        
        public ReportQuotaRequest() {
        }
        
        public ReportQuotaRequest(SahinRektefiyeSoln.JetSms.ReportQuotaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportQuotaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ReportQuotaRequestBody() {
        }
        
        public ReportQuotaRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReportQuotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReportQuotaResponse", Namespace="https://www.jetsms.net/soap/", Order=0)]
        public SahinRektefiyeSoln.JetSms.ReportQuotaResponseBody Body;
        
        public ReportQuotaResponse() {
        }
        
        public ReportQuotaResponse(SahinRektefiyeSoln.JetSms.ReportQuotaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.jetsms.net/soap/")]
    public partial class ReportQuotaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReportQuotaResult;
        
        public ReportQuotaResponseBody() {
        }
        
        public ReportQuotaResponseBody(string ReportQuotaResult) {
            this.ReportQuotaResult = ReportQuotaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : SahinRektefiyeSoln.JetSms.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<SahinRektefiyeSoln.JetSms.SMSServiceSoap>, SahinRektefiyeSoln.JetSms.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.SendSMSResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendSMS(SahinRektefiyeSoln.JetSms.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendSMS(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            SahinRektefiyeSoln.JetSms.SendSMSRequest inValue = new SahinRektefiyeSoln.JetSms.SendSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            SahinRektefiyeSoln.JetSms.SendSMSResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendSMSAsync(SahinRektefiyeSoln.JetSms.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSResponse> SendSMSAsync(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            SahinRektefiyeSoln.JetSms.SendSMSRequest inValue = new SahinRektefiyeSoln.JetSms.SendSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendTCKNSMS(SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest request) {
            return base.Channel.SendTCKNSMS(request);
        }
        
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendTCKNSMS(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest inValue = new SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendTCKNSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendTCKNSMS(inValue);
            return retVal.Body.SendTCKNSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendTCKNSMSAsync(SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest request) {
            return base.Channel.SendTCKNSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendTCKNSMSResponse> SendTCKNSMSAsync(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents) {
            SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest inValue = new SahinRektefiyeSoln.JetSms.SendTCKNSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendTCKNSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendTCKNSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendSMSAdvanced(SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest request) {
            return base.Channel.SendSMSAdvanced(request);
        }
        
        public SahinRektefiyeSoln.JetSms.SendSMSResult SendSMSAdvanced(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents, string messageType, SahinRektefiyeSoln.JetSms.ArrayOfString messageHeader) {
            SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest inValue = new SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            inValue.Body.messageType = messageType;
            inValue.Body.messageHeader = messageHeader;
            SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendSMSAdvanced(inValue);
            return retVal.Body.SendSMSAdvancedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.SendSMSAdvancedAsync(SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest request) {
            return base.Channel.SendSMSAdvancedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.SendSMSAdvancedResponse> SendSMSAdvancedAsync(string user, string password, string originator, string reference, string startdate, string expiredate, SahinRektefiyeSoln.JetSms.ArrayOfString messages, SahinRektefiyeSoln.JetSms.ArrayOfString receipents, string messageType, SahinRektefiyeSoln.JetSms.ArrayOfString messageHeader) {
            SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest inValue = new SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.SendSMSAdvancedRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.originator = originator;
            inValue.Body.reference = reference;
            inValue.Body.startdate = startdate;
            inValue.Body.expiredate = expiredate;
            inValue.Body.messages = messages;
            inValue.Body.receipents = receipents;
            inValue.Body.messageType = messageType;
            inValue.Body.messageHeader = messageHeader;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).SendSMSAdvancedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.ReportSMSResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportSMS(SahinRektefiyeSoln.JetSms.ReportSMSRequest request) {
            return base.Channel.ReportSMS(request);
        }
        
        public SahinRektefiyeSoln.JetSms.ReportSMSResult[] ReportSMS(string user, string password, string groupid, string status) {
            SahinRektefiyeSoln.JetSms.ReportSMSRequest inValue = new SahinRektefiyeSoln.JetSms.ReportSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.groupid = groupid;
            inValue.Body.status = status;
            SahinRektefiyeSoln.JetSms.ReportSMSResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportSMS(inValue);
            return retVal.Body.ReportSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportSMSResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportSMSAsync(SahinRektefiyeSoln.JetSms.ReportSMSRequest request) {
            return base.Channel.ReportSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportSMSResponse> ReportSMSAsync(string user, string password, string groupid, string status) {
            SahinRektefiyeSoln.JetSms.ReportSMSRequest inValue = new SahinRektefiyeSoln.JetSms.ReportSMSRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportSMSRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.groupid = groupid;
            inValue.Body.status = status;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.ReportOriginatorResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportOriginator(SahinRektefiyeSoln.JetSms.ReportOriginatorRequest request) {
            return base.Channel.ReportOriginator(request);
        }
        
        public SahinRektefiyeSoln.JetSms.ArrayOfString ReportOriginator(string user, string password) {
            SahinRektefiyeSoln.JetSms.ReportOriginatorRequest inValue = new SahinRektefiyeSoln.JetSms.ReportOriginatorRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportOriginatorRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            SahinRektefiyeSoln.JetSms.ReportOriginatorResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportOriginator(inValue);
            return retVal.Body.ReportOriginatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportOriginatorResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportOriginatorAsync(SahinRektefiyeSoln.JetSms.ReportOriginatorRequest request) {
            return base.Channel.ReportOriginatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportOriginatorResponse> ReportOriginatorAsync(string user, string password) {
            SahinRektefiyeSoln.JetSms.ReportOriginatorRequest inValue = new SahinRektefiyeSoln.JetSms.ReportOriginatorRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportOriginatorRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportOriginatorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SahinRektefiyeSoln.JetSms.ReportQuotaResponse SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportQuota(SahinRektefiyeSoln.JetSms.ReportQuotaRequest request) {
            return base.Channel.ReportQuota(request);
        }
        
        public string ReportQuota(string user, string password) {
            SahinRektefiyeSoln.JetSms.ReportQuotaRequest inValue = new SahinRektefiyeSoln.JetSms.ReportQuotaRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportQuotaRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            SahinRektefiyeSoln.JetSms.ReportQuotaResponse retVal = ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportQuota(inValue);
            return retVal.Body.ReportQuotaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportQuotaResponse> SahinRektefiyeSoln.JetSms.SMSServiceSoap.ReportQuotaAsync(SahinRektefiyeSoln.JetSms.ReportQuotaRequest request) {
            return base.Channel.ReportQuotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SahinRektefiyeSoln.JetSms.ReportQuotaResponse> ReportQuotaAsync(string user, string password) {
            SahinRektefiyeSoln.JetSms.ReportQuotaRequest inValue = new SahinRektefiyeSoln.JetSms.ReportQuotaRequest();
            inValue.Body = new SahinRektefiyeSoln.JetSms.ReportQuotaRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((SahinRektefiyeSoln.JetSms.SMSServiceSoap)(this)).ReportQuotaAsync(inValue);
        }
    }
}
