//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracDetay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AracDetay()
        {
            this.Arac = new HashSet<Arac>();
        }
    
        public int AracDetayId { get; set; }
        public Nullable<System.DateTime> TrafigeCikisTarihi { get; set; }
        public Nullable<System.DateTime> GarantiBsgTrh { get; set; }
        public Nullable<System.DateTime> GarantiBtsTrh { get; set; }
        public Nullable<System.DateTime> EgsozMuayeneBsgTrh { get; set; }
        public Nullable<System.DateTime> EgsozMuayeneBtsTrh { get; set; }
        public Nullable<System.DateTime> MuayeneBsgTrh { get; set; }
        public Nullable<System.DateTime> MuayeneBtsTrh { get; set; }
        public Nullable<System.DateTime> TrafikSigortasiBsgTrh { get; set; }
        public Nullable<System.DateTime> TrafikSigortasiBtsTrh { get; set; }
        public Nullable<System.DateTime> KaskoBsgTrh { get; set; }
        public Nullable<System.DateTime> KaskoBtsTrh { get; set; }
        public string AracSerisi { get; set; }
        public string SanzimanTipi { get; set; }
        public string MotorTipi { get; set; }
        public string SilindirSayisi { get; set; }
        public string AnahtarKodu { get; set; }
        public string TrimTipi { get; set; }
        public string YakitDeposu { get; set; }
        public string GovdeTipi { get; set; }
        public string DepoKodu { get; set; }
        public string SubapAdet { get; set; }
        public string OturmaYeri { get; set; }
        public string MotorHacmi { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arac> Arac { get; set; }
    }
}
