//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapInputQuality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CapInputQuality()
        {
            this.Talepler1 = new HashSet<Talepler>();
        }
    
        public int KapakGirisKaliteId { get; set; }
        public Nullable<int> TalepId { get; set; }
        public string KapakDolapNo { get; set; }
        public string MotorDolapNo { get; set; }
        public string IzinVerilenMinKapakKalinligi { get; set; }
        public string IzinVerilenMaxKapakEgriligi { get; set; }
        public string OlculenKapakKalinligi { get; set; }
        public string OlculenKapakEgriligi { get; set; }
        public string IncelemeSonuclari { get; set; }
        public string YapilacakIslemler { get; set; }
        public string OzelIslemler { get; set; }
        public string OzelUretimler { get; set; }
        public string YedekParcaGirisKontrol { get; set; }
        public Nullable<System.DateTime> ParcaGirisTarihi { get; set; }
        public string TeslimAlan { get; set; }
        public string SupapDusukluguYuksekligi { get; set; }
        public string GerceklestirilenTasmaMiktari { get; set; }
        public string RevizyonSonrasiKapakKalinligi { get; set; }
        public string SupapAyariEmme { get; set; }
        public string SupapAyariEgzoz { get; set; }
        public string YatakSikmaTorku1 { get; set; }
        public string YatakSikmaTorku2 { get; set; }
        public string YatakSikmaTorku3 { get; set; }
        public string YatakSikmaTorku4 { get; set; }
        public string KapakSikmaTorku1 { get; set; }
        public string KapakSikmaTorku2 { get; set; }
        public string KapakSikmaTorku3 { get; set; }
        public string KapakSikmaTorku4 { get; set; }
        public string YapilanIsler { get; set; }
        public string Aciklama { get; set; }
        public string Olusturan { get; set; }
        public Nullable<System.DateTime> OlusturmaTarihi { get; set; }
        public string GerekliParcalar { get; set; }
        public string GerekliParcaAdet { get; set; }
        public string GerekliParcaYorumlar { get; set; }
    
        public virtual Talepler Talepler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talepler> Talepler1 { get; set; }
    }
}
