//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeRequest
    {
        public int ChangeRequestId { get; set; }
        public string ChangeReqDesc { get; set; }
        public string PageUrl { get; set; }
        public Nullable<decimal> Efor { get; set; }
        public bool SwBedelsiz { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
    }
}
