//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepoRafTanim
    {
        public int DepoRafTanimId { get; set; }
        public string DepoSirasi { get; set; }
        public string DepoRafi { get; set; }
        public string DepoHucresi { get; set; }
        public string Aciklama { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> DtCreated { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> DtModified { get; set; }
    }
}
