//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngineInformationDet
    {
        public int EngineInfoDetId { get; set; }
        public Nullable<int> EngineInfoHdrId { get; set; }
        public string EngineInfoDetDesc { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsContainPiece { get; set; }
    
        public virtual EngineInformationHdr EngineInformationHdr { get; set; }
    }
}
