//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Irsaliyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Irsaliyeler()
        {
            this.Irsaliyeler1 = new HashSet<Irsaliyeler>();
        }
    
        public int IrsaliyeId { get; set; }
        public string FaturaNo { get; set; }
        public int TedarikciId { get; set; }
        public Nullable<int> Vade { get; set; }
        public System.DateTime FaturaTarihi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public decimal ToplamTutar { get; set; }
        public decimal ToplamIskonto { get; set; }
        public decimal HesaplananKdv { get; set; }
        public decimal FaturaToplam { get; set; }
        public int IrsaliyeStatu { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> IadeIrsaliyeId { get; set; }
        public bool SwIslendiMi { get; set; }
        public Nullable<System.DateTime> IslenmeTarihi { get; set; }
        public string IsleyenKisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Irsaliyeler> Irsaliyeler1 { get; set; }
        public virtual Irsaliyeler Irsaliyeler2 { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
