//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iscilikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Iscilikler()
        {
            this.IsEmriKalemleri = new HashSet<IsEmriKalemleri>();
            this.PaketIscilikleri = new HashSet<PaketIscilikleri>();
            this.TeklifKalemleri = new HashSet<TeklifKalemleri>();
        }
    
        public int IscilikId { get; set; }
        public string IscilikKodu { get; set; }
        public string IscilikAdi { get; set; }
        public decimal BirimSaat { get; set; }
        public int IscilikTipId { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> IscilikLogoId { get; set; }
    
        public virtual IscilikTipleri IscilikTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriKalemleri> IsEmriKalemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketIscilikleri> PaketIscilikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifKalemleri> TeklifKalemleri { get; set; }
    }
}
