//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsEmirleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IsEmirleri()
        {
            this.IsEmriBelirtiKodlari = new HashSet<IsEmriBelirtiKodlari>();
            this.IsEmriDosyalari = new HashSet<IsEmriDosyalari>();
            this.IsEmriKalemleri = new HashSet<IsEmriKalemleri>();
            this.KlimaFixing = new HashSet<KlimaFixing>();
            this.MarsMotorFixing = new HashSet<MarsMotorFixing>();
            this.SanzimanFixing = new HashSet<SanzimanFixing>();
            this.Teklifler = new HashSet<Teklifler>();
            this.TurboSarjFixing = new HashSet<TurboSarjFixing>();
        }
    
        public int IsEmriId { get; set; }
        public int MusteriId { get; set; }
        public Nullable<int> AracId { get; set; }
        public int DanismanId { get; set; }
        public int IsEmriTipId { get; set; }
        public Nullable<int> AraciTeslimEdenMusteriId { get; set; }
        public Nullable<int> AraciTeslimAlanMusteriId { get; set; }
        public bool SwVip { get; set; }
        public bool SwInteraktif { get; set; }
        public bool SwTekrarlananIs { get; set; }
        public Nullable<System.DateTime> TahminiTeslimTarihi { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int IsEmriStatuId { get; set; }
        public string IptalNedeni { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<System.DateTime> IsEmriTarihi { get; set; }
        public Nullable<int> IsEmriLogoId { get; set; }
        public Nullable<int> Km { get; set; }
        public string Notlar { get; set; }
        public Nullable<decimal> KDVsizTutar { get; set; }
        public Nullable<decimal> ToplamKDV { get; set; }
        public Nullable<decimal> ToplamIskonto { get; set; }
        public Nullable<decimal> KDVliTutar { get; set; }
        public Nullable<int> IsEmriTeklifStatusu { get; set; }
        public Nullable<System.DateTime> Dt_Teklif_Iletildi { get; set; }
        public Nullable<System.DateTime> Dt_Teklif_Onaylandi { get; set; }
        public Nullable<System.DateTime> Dt_Islem_Tamamlandi { get; set; }
        public string MuhasebeNotu { get; set; }
        public Nullable<int> FaturaTipi { get; set; }
        public bool SwWarranty { get; set; }
        public bool SwRevision { get; set; }
        public string AracTeslimEdenKisi { get; set; }
        public string SerialNo { get; set; }
        public string PartNo { get; set; }
        public bool SwBedelsizOnay { get; set; }
        public string BedelsizAciklamasi { get; set; }
        public Nullable<System.DateTime> DtBedelsizOnayGonderilenTarih { get; set; }
        public string CdBedelsizOnayGonderenKisi { get; set; }
        public Nullable<System.DateTime> DtBedelsizOnayTarihi { get; set; }
        public string CdBedelsizOnaylayanKisi { get; set; }
        public Nullable<System.DateTime> DtBedelsizRedTarihi { get; set; }
        public string CdBedelsizRedEdenKisi { get; set; }
        public Nullable<System.DateTime> Dt_Servis_Bekliyor { get; set; }
        public Nullable<System.DateTime> Dt_Teklif_Iletilmesi_Bekleniyor { get; set; }
        public Nullable<System.DateTime> Dt_Islemde { get; set; }
        public Nullable<int> FaturalanacakMusteriId { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Danismanlar Danismanlar { get; set; }
        public virtual IsEmriStatu IsEmriStatu { get; set; }
        public virtual IsEmriTipleri IsEmriTipleri { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Musteri Musteri1 { get; set; }
        public virtual Musteri Musteri2 { get; set; }
        public virtual Musteri Musteri3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriBelirtiKodlari> IsEmriBelirtiKodlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriDosyalari> IsEmriDosyalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriKalemleri> IsEmriKalemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlimaFixing> KlimaFixing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarsMotorFixing> MarsMotorFixing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanzimanFixing> SanzimanFixing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teklifler> Teklifler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurboSarjFixing> TurboSarjFixing { get; set; }
    }
}
