//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetails
    {
        public int JobDetailId { get; set; }
        public int JobId { get; set; }
        public Nullable<int> ExecutionTime { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public bool isFault { get; set; }
        public string ErrorMsg { get; set; }
        public string StackTrace { get; set; }
        public string CreatedBy { get; set; }
        public string SpoolFilePath { get; set; }
    
        public virtual Jobs Jobs { get; set; }
    }
}
