//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jobs()
        {
            this.JobDetails = new HashSet<JobDetails>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public bool SwActive { get; set; }
        public string JobDesc { get; set; }
        public bool SwPazartesi { get; set; }
        public Nullable<System.DateTime> ExecTimePazatesi { get; set; }
        public bool SwSali { get; set; }
        public Nullable<System.DateTime> ExecTimeSali { get; set; }
        public bool SwCarsamba { get; set; }
        public Nullable<System.DateTime> ExecTimeCarsamba { get; set; }
        public bool SwPersembe { get; set; }
        public Nullable<System.DateTime> ExecTimePersembe { get; set; }
        public bool SwCuma { get; set; }
        public Nullable<System.DateTime> ExecTimeCuma { get; set; }
        public bool SwCumartesi { get; set; }
        public Nullable<System.DateTime> ExecTimeCumartesi { get; set; }
        public bool SwPazar { get; set; }
        public Nullable<System.DateTime> ExecTimePazar { get; set; }
        public bool IsLastExecSuccess { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobDetails> JobDetails { get; set; }
    }
}
