//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlimaFixing
    {
        public int KlimaFixId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public bool SwKasnakKisimHasar { get; set; }
        public bool SwPleytKisimHasar { get; set; }
        public bool SwBobinHasar { get; set; }
        public bool SwRulmanHasar { get; set; }
        public bool SwBasincValfAriza { get; set; }
        public bool SwGovdeHasar { get; set; }
        public bool SwKapakHasar { get; set; }
        public bool SwKompleKlimaKompHasar { get; set; }
        public string TespitAciklama { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> IsEmriId { get; set; }
    
        public virtual IsEmirleri IsEmirleri { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
