//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlimaRevisionTypes
    {
        public int KlimaRevisionTypeId { get; set; }
        public string RevisionDesc { get; set; }
        public bool SwOring { get; set; }
        public bool SwKavramaRulmani { get; set; }
        public bool SwBasincValfi { get; set; }
        public bool SwKasnak { get; set; }
        public bool SwKompleBobinSet { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
