//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KvkMusteriLogs
    {
        public int LogId { get; set; }
        public int MusteriId { get; set; }
        public string LogDesc { get; set; }
        public System.DateTime LogDate { get; set; }
        public string IP { get; set; }
    
        public virtual Musteri Musteri { get; set; }
    }
}
