//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_001_SRVCARD
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<short> CARDTYPE { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<int> PAYMENTREF { get; set; }
        public Nullable<int> UNITSETREF { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<double> RETURNVAT { get; set; }
        public Nullable<short> IMPORTEXPNS { get; set; }
        public Nullable<short> AFFECTCOST { get; set; }
        public Nullable<int> ADDTAXREF { get; set; }
        public Nullable<short> DISTTYPE { get; set; }
        public Nullable<int> EXTACCESSFLAGS { get; set; }
        public Nullable<short> USEDINPERIODS { get; set; }
        public Nullable<short> CANDEDUCT { get; set; }
        public Nullable<short> DEDUCTIONPART1 { get; set; }
        public Nullable<short> DEDUCTIONPART2 { get; set; }
        public Nullable<short> EXEMPTFROMTAXDECL { get; set; }
        public Nullable<short> CURRDIFF { get; set; }
        public string DEDUCTCODE { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public string DEFINITION2 { get; set; }
        public Nullable<int> PARENTSRVREF { get; set; }
        public Nullable<int> LOWLEVELCODES1 { get; set; }
        public Nullable<int> LOWLEVELCODES2 { get; set; }
        public Nullable<int> LOWLEVELCODES3 { get; set; }
        public Nullable<int> LOWLEVELCODES4 { get; set; }
        public Nullable<int> LOWLEVELCODES5 { get; set; }
        public Nullable<int> LOWLEVELCODES6 { get; set; }
        public Nullable<int> LOWLEVELCODES7 { get; set; }
        public Nullable<int> LOWLEVELCODES8 { get; set; }
        public Nullable<int> LOWLEVELCODES9 { get; set; }
        public Nullable<int> LOWLEVELCODES10 { get; set; }
        public string SPECODE2 { get; set; }
        public string SPECODE3 { get; set; }
        public string SPECODE4 { get; set; }
        public string SPECODE5 { get; set; }
        public Nullable<short> MULTIADDTAX { get; set; }
        public string GTIPCODE { get; set; }
        public string CPACODE { get; set; }
        public Nullable<int> PUBLICCOUNTRYREF { get; set; }
        public Nullable<int> OPPOSESRVREF { get; set; }
        public Nullable<short> VEHICLEEXP { get; set; }
        public Nullable<short> VEHICLERENT { get; set; }
    }
}
