//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_001_01_STFICHE
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> GRPCODE { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public Nullable<short> IOCODE { get; set; }
        public string FICHENO { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<int> FTIME { get; set; }
        public string DOCODE { get; set; }
        public string INVNO { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public Nullable<int> INVOICEREF { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public Nullable<int> RECVREF { get; set; }
        public Nullable<int> ACCOUNTREF { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<int> PRODORDERREF { get; set; }
        public string PORDERFICHENO { get; set; }
        public Nullable<short> SOURCETYPE { get; set; }
        public Nullable<short> SOURCEINDEX { get; set; }
        public Nullable<int> SOURCEWSREF { get; set; }
        public Nullable<int> SOURCEPOLNREF { get; set; }
        public Nullable<short> SOURCECOSTGRP { get; set; }
        public Nullable<short> DESTTYPE { get; set; }
        public Nullable<short> DESTINDEX { get; set; }
        public Nullable<int> DESTWSREF { get; set; }
        public Nullable<int> DESTPOLNREF { get; set; }
        public Nullable<short> DESTCOSTGRP { get; set; }
        public Nullable<short> FACTORYNR { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<short> COMPBRANCH { get; set; }
        public Nullable<short> COMPDEPARTMENT { get; set; }
        public Nullable<short> COMPFACTORY { get; set; }
        public Nullable<short> PRODSTAT { get; set; }
        public Nullable<short> DEVIR { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public Nullable<short> BILLED { get; set; }
        public Nullable<short> ACCOUNTED { get; set; }
        public Nullable<short> UPDCURR { get; set; }
        public Nullable<short> INUSE { get; set; }
        public Nullable<short> INVKIND { get; set; }
        public Nullable<double> ADDDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTED { get; set; }
        public Nullable<double> ADDEXPENSES { get; set; }
        public Nullable<double> TOTALEXPENSES { get; set; }
        public Nullable<double> TOTALDEPOZITO { get; set; }
        public Nullable<double> TOTALPROMOTIONS { get; set; }
        public Nullable<double> TOTALVAT { get; set; }
        public Nullable<double> GROSSTOTAL { get; set; }
        public Nullable<double> NETTOTAL { get; set; }
        public string GENEXP1 { get; set; }
        public string GENEXP2 { get; set; }
        public string GENEXP3 { get; set; }
        public string GENEXP4 { get; set; }
        public string GENEXP5 { get; set; }
        public string GENEXP6 { get; set; }
        public Nullable<double> REPORTRATE { get; set; }
        public Nullable<double> REPORTNET { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<int> PAYDEFREF { get; set; }
        public Nullable<short> PRINTCNT { get; set; }
        public Nullable<short> FICHECNT { get; set; }
        public Nullable<int> ACCFICHEREF { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<int> SALESMANREF { get; set; }
        public Nullable<short> CANCELLEDACC { get; set; }
        public string SHPTYPCOD { get; set; }
        public string SHPAGNCOD { get; set; }
        public string TRACKNR { get; set; }
        public Nullable<short> GENEXCTYP { get; set; }
        public Nullable<short> LINEEXCTYP { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<int> SHIPINFOREF { get; set; }
        public Nullable<int> DISTORDERREF { get; set; }
        public Nullable<short> SENDCNT { get; set; }
        public Nullable<short> DLVCLIENT { get; set; }
        public string DOCTRACKINGNR { get; set; }
        public Nullable<short> ADDTAXCALC { get; set; }
        public Nullable<double> TOTALADDTAX { get; set; }
        public string UGIRTRACKINGNO { get; set; }
        public Nullable<int> QPRODFCREF { get; set; }
        public Nullable<int> VAACCREF { get; set; }
        public Nullable<int> VACENTERREF { get; set; }
        public string ORGLOGOID { get; set; }
        public Nullable<short> FROMEXIM { get; set; }
        public string FRGTYPCOD { get; set; }
        public Nullable<short> TRCURR { get; set; }
        public Nullable<double> TRRATE { get; set; }
        public Nullable<double> TRNET { get; set; }
        public Nullable<int> EXIMWHFCREF { get; set; }
        public Nullable<short> EXIMFCTYPE { get; set; }
        public Nullable<int> MAINSTFCREF { get; set; }
        public Nullable<short> FROMORDWITHPAY { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public Nullable<int> WFLOWCRDREF { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> UPDTRCURR { get; set; }
        public Nullable<double> TOTALEXADDTAX { get; set; }
        public Nullable<short> AFFECTCOLLATRL { get; set; }
        public Nullable<short> DEDUCTIONPART1 { get; set; }
        public Nullable<short> DEDUCTIONPART2 { get; set; }
        public Nullable<short> GRPFIRMTRANS { get; set; }
        public Nullable<short> AFFECTRISK { get; set; }
        public Nullable<short> DISPSTATUS { get; set; }
        public Nullable<short> APPROVE { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
        public Nullable<short> CANTCREDEDUCT { get; set; }
        public Nullable<System.DateTime> SHIPDATE { get; set; }
        public Nullable<int> SHIPTIME { get; set; }
        public Nullable<short> ENTRUSTDEVIR { get; set; }
        public Nullable<int> RELTRANSFCREF { get; set; }
        public Nullable<short> FROMTRANSFER { get; set; }
        public string GUID { get; set; }
        public string GLOBALID { get; set; }
        public Nullable<int> COMPSTFCREF { get; set; }
        public Nullable<int> COMPINVREF { get; set; }
        public Nullable<double> TOTALSERVICES { get; set; }
        public string CAMPAIGNCODE { get; set; }
        public Nullable<int> OFFERREF { get; set; }
        public Nullable<short> EINVOICETYP { get; set; }
        public Nullable<short> EINVOICE { get; set; }
        public Nullable<short> NOCALCULATE { get; set; }
        public Nullable<short> PRODORDERTYP { get; set; }
        public Nullable<short> QPRODFCTYP { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public Nullable<short> PRDORDSLPLNRESERVE { get; set; }
        public Nullable<short> CONTROLINFO { get; set; }
        public Nullable<short> EDESPATCH { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<int> DOCTIME { get; set; }
        public Nullable<short> EDESPSTATUS { get; set; }
        public Nullable<short> PROFILEID { get; set; }
        public string DELIVERYCODE { get; set; }
        public Nullable<short> DESTSTATUS { get; set; }
        public string CANCELEXP { get; set; }
        public string UNDOEXP { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public Nullable<short> CREATEWHERE { get; set; }
        public Nullable<int> PUBLICBNACCREF { get; set; }
        public Nullable<short> ACCEPTEINVPUBLIC { get; set; }
        public string VATEXCEPTCODE { get; set; }
        public string VATEXCEPTREASON { get; set; }
        public string ATAXEXCEPTCODE { get; set; }
        public string ATAXEXCEPTREASON { get; set; }
        public Nullable<short> TAXFREECHX { get; set; }
        public Nullable<int> MNTORDERFREF { get; set; }
        public string PRINTEDDESPFCNO { get; set; }
    }
}
