//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_001_01_INVOICE
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> GRPCODE { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public string FICHENO { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<int> TIME_ { get; set; }
        public string DOCODE { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public Nullable<int> RECVREF { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<int> ACCOUNTREF { get; set; }
        public Nullable<short> SOURCEINDEX { get; set; }
        public Nullable<short> SOURCECOSTGRP { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public Nullable<short> ACCOUNTED { get; set; }
        public Nullable<short> PAIDINCASH { get; set; }
        public Nullable<short> FROMKASA { get; set; }
        public Nullable<short> ENTEGSET { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ADDDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTED { get; set; }
        public Nullable<double> ADDEXPENSES { get; set; }
        public Nullable<double> TOTALEXPENSES { get; set; }
        public Nullable<double> DISTEXPENSE { get; set; }
        public Nullable<double> TOTALDEPOZITO { get; set; }
        public Nullable<double> TOTALPROMOTIONS { get; set; }
        public Nullable<double> VATINCGROSS { get; set; }
        public Nullable<double> TOTALVAT { get; set; }
        public Nullable<double> GROSSTOTAL { get; set; }
        public Nullable<double> NETTOTAL { get; set; }
        public string GENEXP1 { get; set; }
        public string GENEXP2 { get; set; }
        public string GENEXP3 { get; set; }
        public string GENEXP4 { get; set; }
        public string GENEXP5 { get; set; }
        public string GENEXP6 { get; set; }
        public Nullable<double> INTERESTAPP { get; set; }
        public Nullable<short> TRCURR { get; set; }
        public Nullable<double> TRRATE { get; set; }
        public Nullable<double> TRNET { get; set; }
        public Nullable<double> REPORTRATE { get; set; }
        public Nullable<double> REPORTNET { get; set; }
        public Nullable<short> ONLYONEPAYLINE { get; set; }
        public Nullable<int> KASTRANSREF { get; set; }
        public Nullable<int> PAYDEFREF { get; set; }
        public Nullable<short> PRINTCNT { get; set; }
        public Nullable<short> GVATINC { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<int> ACCFICHEREF { get; set; }
        public Nullable<int> ADDEXPACCREF { get; set; }
        public Nullable<int> ADDEXPCENTREF { get; set; }
        public Nullable<short> DECPRDIFF { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<int> SALESMANREF { get; set; }
        public Nullable<short> CANCELLEDACC { get; set; }
        public string SHPTYPCOD { get; set; }
        public string SHPAGNCOD { get; set; }
        public string TRACKNR { get; set; }
        public Nullable<short> GENEXCTYP { get; set; }
        public Nullable<short> LINEEXCTYP { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<short> FACTORYNR { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<int> SHIPINFOREF { get; set; }
        public Nullable<int> DISTORDERREF { get; set; }
        public Nullable<short> SENDCNT { get; set; }
        public Nullable<short> DLVCLIENT { get; set; }
        public Nullable<int> COSTOFSALEFCREF { get; set; }
        public Nullable<short> OPSTAT { get; set; }
        public string DOCTRACKINGNR { get; set; }
        public Nullable<double> TOTALADDTAX { get; set; }
        public Nullable<short> PAYMENTTYPE { get; set; }
        public Nullable<double> INFIDX { get; set; }
        public Nullable<short> ACCOUNTEDCNT { get; set; }
        public string ORGLOGOID { get; set; }
        public Nullable<short> FROMEXIM { get; set; }
        public string FRGTYPCOD { get; set; }
        public Nullable<short> EXIMFCTYPE { get; set; }
        public Nullable<short> FROMORDWITHPAY { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public Nullable<int> WFLOWCRDREF { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> DEDUCTIONPART1 { get; set; }
        public Nullable<short> DEDUCTIONPART2 { get; set; }
        public Nullable<double> TOTALEXADDTAX { get; set; }
        public Nullable<short> EXACCOUNTED { get; set; }
        public Nullable<short> FROMBANK { get; set; }
        public Nullable<int> BNTRANSREF { get; set; }
        public Nullable<short> AFFECTCOLLATRL { get; set; }
        public Nullable<short> GRPFIRMTRANS { get; set; }
        public Nullable<short> AFFECTRISK { get; set; }
        public Nullable<short> CONTROLINFO { get; set; }
        public Nullable<short> POSTRANSFERINFO { get; set; }
        public Nullable<short> TAXFREECHX { get; set; }
        public string PASSPORTNO { get; set; }
        public string CREDITCARDNO { get; set; }
        public Nullable<short> INEFFECTIVECOST { get; set; }
        public Nullable<short> REFLECTED { get; set; }
        public Nullable<int> REFLACCFICHEREF { get; set; }
        public Nullable<short> CANCELLEDREFLACC { get; set; }
        public string CREDITCARDNUM { get; set; }
        public Nullable<short> APPROVE { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
        public Nullable<short> CANTCREDEDUCT { get; set; }
        public Nullable<short> ENTRUST { get; set; }
        public Nullable<System.DateTime> DOCDATE { get; set; }
        public Nullable<short> EINVOICE { get; set; }
        public Nullable<short> PROFILEID { get; set; }
        public string GUID { get; set; }
        public Nullable<short> ESTATUS { get; set; }
        public Nullable<System.DateTime> ESTARTDATE { get; set; }
        public Nullable<System.DateTime> EENDDATE { get; set; }
        public string EDESCRIPTION { get; set; }
        public Nullable<double> EDURATION { get; set; }
        public Nullable<short> EDURATIONTYPE { get; set; }
        public Nullable<short> DEVIR { get; set; }
        public Nullable<double> DISTADJPRICEUFRS { get; set; }
        public Nullable<int> COSFCREFUFRS { get; set; }
        public string GLOBALID { get; set; }
        public Nullable<double> TOTALSERVICES { get; set; }
        public Nullable<short> FROMLEASING { get; set; }
        public string CANCELEXP { get; set; }
        public string UNDOEXP { get; set; }
        public string VATEXCEPTREASON { get; set; }
        public string CAMPAIGNCODE { get; set; }
        public Nullable<short> CANCELDESPSINV { get; set; }
        public Nullable<short> FROMEXCHDIFF { get; set; }
        public Nullable<short> EXIMVAT { get; set; }
        public string SERIALCODE { get; set; }
        public Nullable<short> APPCLDEDUCTLIM { get; set; }
        public Nullable<short> EINVOICETYP { get; set; }
        public string VATEXCEPTCODE { get; set; }
        public Nullable<int> OFFERREF { get; set; }
        public string ATAXEXCEPTREASON { get; set; }
        public string ATAXEXCEPTCODE { get; set; }
        public Nullable<short> FROMSTAFFOTHEREX { get; set; }
        public Nullable<short> NOCALCULATE { get; set; }
        public Nullable<short> INSTEADOFDESP { get; set; }
        public Nullable<short> OKCFICHE { get; set; }
        public Nullable<System.DateTime> CANCELDATE { get; set; }
        public string FRGTYPDESC { get; set; }
        public Nullable<int> MARKREF { get; set; }
        public Nullable<System.DateTime> PRINTDATE { get; set; }
        public string DELIVERCODE { get; set; }
        public Nullable<short> ACCEPTEINVPUBLIC { get; set; }
        public Nullable<int> PUBLICBNACCREF { get; set; }
        public string TYPECODE { get; set; }
        public Nullable<short> FUTMNTHYREXPINC { get; set; }
    }
}
