//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LogoEntities : DbContext
    {
        public LogoEntities()
            : base("name=LogoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LG_001_01_INVOICE> LG_001_01_INVOICE { get; set; }
        public virtual DbSet<LG_001_01_STFICHE> LG_001_01_STFICHE { get; set; }
        public virtual DbSet<LG_001_01_STLINE> LG_001_01_STLINE { get; set; }
        public virtual DbSet<LG_001_CLCARD> LG_001_CLCARD { get; set; }
        public virtual DbSet<LG_001_SRVCARD> LG_001_SRVCARD { get; set; }
        public virtual DbSet<LG_001_ITEMS> LG_001_ITEMS { get; set; }
    }
}
