//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailAdresleri
    {
        public int MailAdresId { get; set; }
        public string Mail { get; set; }
        public Nullable<int> MailGrupId { get; set; }
    
        public virtual MailGruplari MailGruplari { get; set; }
    }
}
