//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarsMotorRevisionTypes
    {
        public int MarsMotorRevisionTypeId { get; set; }
        public string RevisionDesc { get; set; }
        public bool SwKomur { get; set; }
        public bool SwBurcRulman { get; set; }
        public bool SwMarsDislisi { get; set; }
        public bool SwMarsOtomatigi { get; set; }
        public bool SwYardimciOtomatik { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VehicleType { get; set; }
    }
}
