//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarsMotorFixing
    {
        public int MarsMotorFixId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public bool SwCatalHasar { get; set; }
        public bool SwKomurAsinma { get; set; }
        public bool SwDislideAsinma { get; set; }
        public bool SwDisliKafasindaAsinma { get; set; }
        public bool SwRediktorDisliAsinma { get; set; }
        public bool SwDebriyajAsinma { get; set; }
        public bool SwPinyonKapakAsinma { get; set; }
        public bool SwOtomatikTamirTakimiAsinma { get; set; }
        public bool SwBurcAsinma { get; set; }
        public bool SwOtomatikAriza { get; set; }
        public bool SwYardimciOtomatikAriza { get; set; }
        public bool SwYastikAriza { get; set; }
        public bool SwKollektorAriza { get; set; }
        public bool SwRulmanAsinma { get; set; }
        public string TespitAciklama { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool SwKomurYuvasindaAsinma { get; set; }
        public bool SwArkaKapaktaAsinma { get; set; }
        public Nullable<int> IsEmriId { get; set; }
    
        public virtual IsEmirleri IsEmirleri { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
