//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string FromSubject { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool SwRead { get; set; }
    }
}
