//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotorOlcuselKontrol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MotorOlcuselKontrol()
        {
            this.Talepler1 = new HashSet<Talepler>();
        }
    
        public int MotorOlcuselKontrolId { get; set; }
        public Nullable<int> TalepId { get; set; }
        public string KapakDolapNo { get; set; }
        public string MotorDolapNo { get; set; }
        public string IzinVerilenMaxEgrilik { get; set; }
        public string TespitEdilenEgrilik { get; set; }
        public string SilindirCaplariStdDeger { get; set; }
        public string SilindirCaplari { get; set; }
        public string MaxAsinma { get; set; }
        public string MaxOvallik { get; set; }
        public string MaxKoniklik { get; set; }
        public string SilindirNo1 { get; set; }
        public string SilindirNo2 { get; set; }
        public string SilindirNo3 { get; set; }
        public string GomlekFaturaStdDeger { get; set; }
        public string GomlekFaturaTasma { get; set; }
        public string GomlekYuvaCapi { get; set; }
        public string PistonCapiStdDeger { get; set; }
        public string PistonCapi { get; set; }
        public string AnaMuyluStdDeger { get; set; }
        public string AnaMuylu { get; set; }
        public string KolMuyluStdDeger { get; set; }
        public string KolMuylu { get; set; }
        public string KrankMiliSalgiDegeri { get; set; }
        public string MotorIncelemeSonuc { get; set; }
    
        public virtual Talepler Talepler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Talepler> Talepler1 { get; set; }
    }
}
