//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAraclari
    {
        public int MusteriAracId { get; set; }
        public int MusteriId { get; set; }
        public int AracId { get; set; }
        public bool SwAktif { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifier { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Musteri Musteri { get; set; }
    }
}
