//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanzimanFixing
    {
        public int SanzimanFixId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public bool SwPistonlardaAsinma { get; set; }
        public bool SwBaltalardaYanma { get; set; }
        public bool SwDirekKavramaTasindaHasar { get; set; }
        public bool SwPleydlerdeYanma { get; set; }
        public bool SwGezegenDislideHasar { get; set; }
        public bool SwGunesDislideHasar { get; set; }
        public bool SwKavramadaHasar { get; set; }
        public bool SwSelenoidKacagi { get; set; }
        public bool SwTekYonluKavramaHasar { get; set; }
        public bool SwVitesCatalindaHasar { get; set; }
        public bool SwDifransiyeldeKirilma { get; set; }
        public string TespitAciklama { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SanzimanType { get; set; }
        public Nullable<int> IsEmriId { get; set; }
    
        public virtual IsEmirleri IsEmirleri { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
