//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SayimDetail
    {
        public int SayimDetailId { get; set; }
        public int SayimHeaderId { get; set; }
        public int StokKartId { get; set; }
        public Nullable<decimal> FiiliStok { get; set; }
        public string Islem { get; set; }
        public Nullable<decimal> Fark { get; set; }
        public Nullable<decimal> SayimStok { get; set; }
        public string Aciklama { get; set; }
    
        public virtual SayimHeader SayimHeader { get; set; }
        public virtual StokKarti StokKarti { get; set; }
    }
}
