//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartiAlternatif
    {
        public int StokKartiAlternatifId { get; set; }
        public int StokKartiBase { get; set; }
        public int StokKartiAlt { get; set; }
    
        public virtual StokKarti StokKarti { get; set; }
        public virtual StokKarti StokKarti1 { get; set; }
    }
}
