//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKarti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StokKarti()
        {
            this.IsEmriKalemleri = new HashSet<IsEmriKalemleri>();
            this.IsEmriKalemleri1 = new HashSet<IsEmriKalemleri>();
            this.PaketStokKartlari = new HashSet<PaketStokKartlari>();
            this.SayimDetail = new HashSet<SayimDetail>();
            this.StokKartiAlternatif = new HashSet<StokKartiAlternatif>();
            this.StokKartiAlternatif1 = new HashSet<StokKartiAlternatif>();
            this.StokKartiDetay = new HashSet<StokKartiDetay>();
            this.TeklifKalemleri = new HashSet<TeklifKalemleri>();
            this.VehicleStoks = new HashSet<VehicleStoks>();
        }
    
        public int StokKartiId { get; set; }
        public string ParcaNo { get; set; }
        public string ParcaAdi { get; set; }
        public int EnAzSatisAdedi { get; set; }
        public Nullable<int> EnAzStokAdedi { get; set; }
        public decimal ToplamStok { get; set; }
        public decimal AtolyeStok { get; set; }
        public decimal SatisBirimFiyati { get; set; }
        public int Kdv { get; set; }
        public int ParcaTipId { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> StokKartLogoId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriKalemleri> IsEmriKalemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsEmriKalemleri> IsEmriKalemleri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaketStokKartlari> PaketStokKartlari { get; set; }
        public virtual ParcaTipleri ParcaTipleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SayimDetail> SayimDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokKartiAlternatif> StokKartiAlternatif { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokKartiAlternatif> StokKartiAlternatif1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokKartiDetay> StokKartiDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeklifKalemleri> TeklifKalemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleStoks> VehicleStoks { get; set; }
    }
}
