//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StokKartiSayimLoglari
    {
        public int StokKartiSayimLogId { get; set; }
        public int SayimHeaderId { get; set; }
        public string Aciklamasi { get; set; }
        public Nullable<decimal> EskiStok { get; set; }
        public Nullable<decimal> YeniStok { get; set; }
    
        public virtual SayimHeader SayimHeader { get; set; }
    }
}
