//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierParts
    {
        public int SupplierPartsId { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string ShipmentNumber { get; set; }
        public string KleymNumber { get; set; }
        public Nullable<int> PartReviewResultId { get; set; }
        public Nullable<int> PartReviewTypeId { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string RevisionTrackNumber { get; set; }
        public Nullable<int> RevisionTypeId { get; set; }
        public Nullable<int> VehicleKm { get; set; }
        public string VIN { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Creator { get; set; }
        public Nullable<int> SupplierCompanyId { get; set; }
        public bool IsSend { get; set; }
        public string RevmerPartDesc { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual PartReviewResult PartReviewResult { get; set; }
        public virtual PartReviewType PartReviewType { get; set; }
        public virtual RevisionType RevisionType { get; set; }
        public virtual Services Services { get; set; }
        public virtual SupplierCompany SupplierCompany { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
