//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Talepler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Talepler()
        {
            this.TalepDetay = new HashSet<TalepDetay>();
            this.MotorOlcuselKontrol = new HashSet<MotorOlcuselKontrol>();
        }
    
        public int TalepId { get; set; }
        public int MusteriId { get; set; }
        public Nullable<int> PartId { get; set; }
        public string ArayanKisi { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<System.DateTime> MusteriAramaTarihi { get; set; }
        public string Note { get; set; }
        public string AtananSofor { get; set; }
        public Nullable<int> Km { get; set; }
        public string VinNo { get; set; }
        public string Plate { get; set; }
        public Nullable<int> AracGrupId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<int> TalepSekliId { get; set; }
        public Nullable<System.DateTime> KargoyaVerilisTarihi { get; set; }
        public Nullable<System.DateTime> AramaTarihi { get; set; }
        public string KargoFirmasi { get; set; }
        public string GönderiKodu { get; set; }
        public Nullable<System.DateTime> MusteriAtolyeGelisTarihi { get; set; }
        public Nullable<int> TalepDosyaId { get; set; }
        public Nullable<int> MotorOlcuselKontrolId { get; set; }
    
        public virtual AracGrubu AracGrubu { get; set; }
        public virtual Musteri Musteri { get; set; }
        public virtual Parts Parts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TalepDetay> TalepDetay { get; set; }
        public virtual TalepDosya TalepDosya { get; set; }
        public virtual TalepSekli TalepSekli { get; set; }
        public virtual Users Users { get; set; }
        public virtual Vehicles Vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MotorOlcuselKontrol> MotorOlcuselKontrol { get; set; }
        public virtual MotorOlcuselKontrol MotorOlcuselKontrol1 { get; set; }
    }
}
