//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeklifKalemleri
    {
        public System.Guid TeklifKalemId { get; set; }
        public System.Guid TeklifId { get; set; }
        public string KalemTipi { get; set; }
        public Nullable<int> IscilikId { get; set; }
        public Nullable<int> StokKartId { get; set; }
        public Nullable<decimal> BirimSaatAdet { get; set; }
        public Nullable<decimal> IskontoOrani { get; set; }
        public Nullable<decimal> BirimIndirimFiyat { get; set; }
        public Nullable<decimal> KalemTutar { get; set; }
        public Nullable<decimal> KDVliKalemTutar { get; set; }
        public Nullable<decimal> MaliyetDyi { get; set; }
        public Nullable<decimal> DyiIlkSatisFiyati { get; set; }
    
        public virtual Iscilikler Iscilikler { get; set; }
        public virtual StokKarti StokKarti { get; set; }
        public virtual Teklifler Teklifler { get; set; }
    }
}
