//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurboRevisionTypes
    {
        public int TurboRevisionTypeId { get; set; }
        public string RevisionDesc { get; set; }
        public bool SwSoketModul { get; set; }
        public bool SwGovde { get; set; }
        public bool SwMil { get; set; }
        public bool SwKompresorCarki { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool SwMinorTakim { get; set; }
        public bool SwMajorTakim { get; set; }
        public string VehicleType { get; set; }
    }
}
