//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadedFordExcels
    {
        public int FordExcelId { get; set; }
        public string FordExcelName { get; set; }
        public string CdFordTypeType { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> SwError { get; set; }
        public string IrsaliyeNo { get; set; }
        public int PartCount { get; set; }
    }
}
