//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAllowedIsEmriTip
    {
        public System.Guid UserAllowedIsEmriTip1 { get; set; }
        public string UserName { get; set; }
        public int IsEmriTipId { get; set; }
        public Nullable<System.DateTime> DtCreated { get; set; }
        public string Creator { get; set; }
    
        public virtual IsEmriTipleri IsEmriTipleri { get; set; }
        public virtual Users Users { get; set; }
    }
}
