//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WayBills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WayBills()
        {
            this.WayBillParts = new HashSet<WayBillParts>();
        }
    
        public int WayBillId { get; set; }
        public int SupplierId { get; set; }
        public string WayBillNo { get; set; }
        public Nullable<System.DateTime> WayBillDate { get; set; }
        public System.DateTime WayBillIncomeDate { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Statu { get; set; }
        public string Title { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WayBillParts> WayBillParts { get; set; }
    }
}
