//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebErrorLogs
    {
        public System.Guid IdLog { get; set; }
        public string UserName { get; set; }
        public System.DateTime DtLog { get; set; }
        public string Page { get; set; }
        public string Error { get; set; }
        public string StackTrace { get; set; }
        public string Parameters { get; set; }
        public string FullUrl { get; set; }
    }
}
