//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahinRektefiyeSoln.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.KlimaFixing = new HashSet<KlimaFixing>();
            this.MarsMotorFixing = new HashSet<MarsMotorFixing>();
            this.SanzimanFixing = new HashSet<SanzimanFixing>();
            this.TurboSarjFixing = new HashSet<TurboSarjFixing>();
        }
    
        public int WorkOrderId { get; set; }
        public int ServiceId { get; set; }
        public int TaskId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public int VehicleId { get; set; }
        public string Plate { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<int> VehicleKm { get; set; }
        public string VIN { get; set; }
        public string ServiceContact { get; set; }
        public string ComplaintsCustomerRequests { get; set; }
        public bool SwWarranty { get; set; }
        public bool SwRevision { get; set; }
        public Nullable<int> Statu { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> SwExWorkShip { get; set; }
        public string ChExWorkShip { get; set; }
        public Nullable<decimal> CsExWorkShip { get; set; }
        public string NoWorkOrder { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public bool SwApproved { get; set; }
        public string NoBill { get; set; }
        public Nullable<int> CsModelYear { get; set; }
        public string CdFuelType { get; set; }
        public bool SwRepeatWork { get; set; }
        public string SerialNo { get; set; }
        public string PartNo { get; set; }
        public bool ReportIsSend { get; set; }
        public bool ReportApprovedByCustomer { get; set; }
        public string IadeIptalAciklamasi { get; set; }
        public string MuhasebeNotu { get; set; }
        public Nullable<int> FaturaTipi { get; set; }
    
        public virtual Companies Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KlimaFixing> KlimaFixing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarsMotorFixing> MarsMotorFixing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanzimanFixing> SanzimanFixing { get; set; }
        public virtual Services Services { get; set; }
        public virtual Tasks Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurboSarjFixing> TurboSarjFixing { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
